export const userData = [
  {
    id: Math.random().toString(36).substring(2, 15),
    name: "John Facili Doe",
    role: "Facilitator",
    phoneNumber: "0710000000",
    email: "john.doe@example.com",
  },
  {
    id: Math.random().toString(36).substring(2, 15),
    name: "Jane Modera Smith",
    role: "Moderator",
    phoneNumber: "0720000000",
    email: "jane.smith@example.com",
  },
  {
    id: Math.random().toString(36).substring(2, 15),
    name: "Alice Facil Brown",
    role: "Facilitator",
    phoneNumber: "0730000000",
    email: "alice.brown@example.com",
  },
  {
    id: Math.random().toString(36).substring(2, 15),
    name: "Bob Modera White",
    role: "Moderator",
    phoneNumber: "0740000000",
    email: "bob.white@example.com",
  },
  {
    id: Math.random().toString(36).substring(2, 15),
    name: "Charlie Facil Green",
    role: "Facilitator",
    phoneNumber: "0750000000",
    email: "charlie.green@example.com",
  },
  {
    id: Math.random().toString(36).substring(2, 15),
    name: "Diana Modera Black",
    role: "Moderator",
    phoneNumber: "0760000000",
    email: "diana.black@example.com",
  },
  {
    id: Math.random().toString(36).substring(2, 15),
    name: "Eve Facil Blue",
    role: "Facilitator",
    phoneNumber: "0770000000",
    email: "eve.blue@example.com",
  },
  {
    id: Math.random().toString(36).substring(2, 15),
    name: "Frank Modera Red",
    role: "Moderator",
    phoneNumber: "0780000000",
    email: "frank.red@example.com",
  },
  {
    id: Math.random().toString(36).substring(2, 15),
    name: "Grace Facil Yellow",
    role: "Facilitator",
    phoneNumber: "0790000000",
    email: "grace.yellow@example.com",
  },
  {
    id: Math.random().toString(36).substring(2, 15),
    name: "Hank Modera Purple",
    role: "Moderator",
    phoneNumber: "0800000000",
    email: "hank.purple@example.com",
  },
  {
    id: Math.random().toString(36).substring(2, 15),
    name: "Ivy Facil Orange",
    role: "Facilitator",
    phoneNumber: "0810000000",
    email: "ivy.orange@example.com",
  },
  {
    id: Math.random().toString(36).substring(2, 15),
    name: "Jack Modera Pink",
    role: "Moderator",
    phoneNumber: "0820000000",
    email: "jack.pink@example.com",
  },
  {
    id: Math.random().toString(36).substring(2, 15),
    name: "Karen Facil Gray",
    role: "Facilitator",
    phoneNumber: "0830000000",
    email: "karen.gray@example.com",
  },
  {
    id: Math.random().toString(36).substring(2, 15),
    name: "Leo Modera Brown",
    role: "Moderator",
    phoneNumber: "0840000000",
    email: "leo.brown@example.com",
  },
];
